definitions:
  handler.Request:
    properties:
      amount:
        type: number
      currency:
        type: string
      date:
        description: 'TODO: con db cambiar a time.Time'
        type: string
      receiver:
        type: string
      sender:
        type: string
      transactionCode:
        type: string
    required:
    - amount
    - currency
    - date
    - receiver
    - sender
    - transactionCode
    type: object
  web.Response:
    properties:
      code:
        type: string
      data: {}
      error:
        type: string
    type: object
info:
  contact: {}
  description: This API Handle MELI Products.
  title: MELI Bootcamp API Lucas
  version: "1.0"
paths:
  /transactions:
    get:
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/web.Response'
      summary: List transactions
  /transactions/:
    post:
      consumes:
      - application/json
      parameters:
      - description: Security Token
        in: header
        name: token
        required: true
        type: string
      - description: Transaction to be created
        in: body
        name: transaction
        required: true
        schema:
          $ref: '#/definitions/handler.Request'
      produces:
      - application/json
      responses:
        "201":
          description: Created
          schema:
            $ref: '#/definitions/web.Response'
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/web.Response'
        "401":
          description: Unauthorized
          schema:
            $ref: '#/definitions/web.Response'
      summary: Create a new transaction
  /transactions/{id}:
    delete:
      parameters:
      - description: transaction ID
        in: path
        name: id
        required: true
        type: integer
      produces:
      - application/json
      responses:
        "204":
          description: No Content
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/web.Response'
        "404":
          description: Not Found
          schema:
            $ref: '#/definitions/web.Response'
      summary: Delete transaction
    get:
      parameters:
      - description: transaction ID
        in: path
        name: id
        required: true
        type: integer
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/web.Response'
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/web.Response'
        "404":
          description: Not Found
          schema:
            $ref: '#/definitions/web.Response'
      summary: Retrieve one transaction
    patch:
      consumes:
      - application/json
      parameters:
      - description: transaction ID
        in: path
        name: id
        required: true
        type: integer
      - description: Updated values of the transaction
        in: body
        name: transaction
        required: true
        schema:
          $ref: '#/definitions/handler.Request'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/web.Response'
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/web.Response'
        "404":
          description: Not Found
          schema:
            $ref: '#/definitions/web.Response'
      summary: Update some values of an existing transaction
    put:
      consumes:
      - application/json
      parameters:
      - description: transaction ID
        in: path
        name: id
        required: true
        type: integer
      - description: Updated values of the transaction
        in: body
        name: transaction
        required: true
        schema:
          $ref: '#/definitions/handler.Request'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/web.Response'
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/web.Response'
        "404":
          description: Not Found
          schema:
            $ref: '#/definitions/web.Response'
      summary: Update existing transaction
swagger: "2.0"
